remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
  
title: Notes (GitHub Version)
description: Matt's Public Reference Links
show_downloads: false

minima:
  nav_pages:
    - README.md
    - AWS.md
    - Bash.md
    - Git.md
    - HL7.md
    - Homelab.md
    - Java.md
    - JavaScript.md
    - Linux.md
    - Python.md